FROM zhayujie/chatgpt-on-wechat:alpine

LABEL maintainer="support@zhenxiang.life"
ARG TZ='Asia/Shanghai'

USER root

RUN apk add --no-cache \
        ffmpeg  \
        espeak \
    && pip install --no-cache \
        baidu-aip \
        chardet \
        SpeechRecognition

# replace entrypoint
ADD ./entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

USER noroot

ENTRYPOINT ["/entrypoint.sh"]